dist: trusty
language: node_js
node_js:
- '12'
- '10'
services:
- rabbitmq
script:
- npm run build -- --declaration
- npm test
after_success:
- test $TRAVIS_NODE_VERSION = "8" && npm run coverage && npm run sendcoverage
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: npm
  email:
    secure: gU5RmWjPYw/fZUPCeQdm0K/wcNlE1Lr9fp7X4ocKMJnyO5sPbh3TmBhHO6IXlHCfyfy2DutEIJf/Ka+xPllQMSKGApGtqiX1HLxyzegCZwf/jtKu4f/vzFjlkn8FbZRZNU1uCtGRdcvvy0OXMaB4Gtf/DOMhMX2UmgijbnFPy2y4YFH8hifcvzkkKqSeHadN1h/PkyLLMipwtD/qyc8avsfB61zsRu4F7daUHbcJUvW+/FfXGWpNcFzZExA9Syz2ezZjjMNbQmVemu9PSvp18hgoE0ekzQQreKUa34k011RI1dZ72wuzGO5rpsaDybxdtDL+qRInrD4oXIqusKay2Rv+bkS4dfCAH+aOdgudMfEJo03Kz+Mvwr4qDakkzCauqb0dvRxD78cZjtke4od29dPtvRYX4DqVdXeNQ7u9TXHIwQq9JQaQHk3EAmOxdpaqFv53Q9z9i68IC0wqgAollJ6IWDkSzxqbaO9frOKPkXeitHKQpX4xYocloZC43RzA1j5PB62JwQPSUNK8g+ZyOvJPMG7+mDka3xql0P39ZCub4fuzyR0m5OVZgE8jWRDLCWhPFj93qXT8ybtuLoRyJoAQUGXzrSs7jhpMKTqdm46i8BbCAgYLYm92TYPi+SdXVhbqsY5onpdn9Z/avUIecLT3ptxg9unjLV8GlTA3A5A=
  api_key:
    secure: x3vSesgwXgw2S7AWad/jYprM/vdtI6pk86F4t+E3gyIuRIksXpGqH/M1pmboyVQAyApfngBRQPXjhcTw3MWD7hJhC6qmhHcSpibfVmtFgZoUnfHyyjfhVbjm5IgPnrjzFbyPzlU7sI/0X3knQWJt711VbYnatyehRZJnORDr8L/Ecyj/bhJLOrDHBu02OFppdyGbGjPcXYSyt71zLH74LxsZedOWUdt9ThIOuJXrV4heV86jMg9RjHDG6PzZmpU5zKiYEgnCsWZEw/wLNKjlFWGDY+m2Z7YJkLKtXC9Ix4MSOel9/hITIcQ6zT0c+zV2n0YunAtxJoGUpHAcQQzd1zz9V8LzfC3UZzKoheBbmv7PD/ERvG62GaLkTWCuaDuRAl9QF/sF9G38QHqfvmtYOhVkKFTDPzsthMzzChT29ya3vPzDFLXrXC2zRRjSp7RefyrYf68n7NGDmf5GO2Tr7d+E0WeNjCvlTBiwvXtCfORos1S64w/MagLaD4jxp4mbmQPaYqiQNaqTGjfga/R5e/O8XGnb3yiGjUGCTwKHciDavj6HDHffMLanCxz/2TNSMjn+fcHqcIp5TUyY6Xns6hivcXABVin4aReAeqDaEP2lX4QUNMUgLvUPTEvXhz+CX5C175WU9pnbRGhl+wAb3AQVGoV/QCiK0isKRuVVkWE=
  on:
    node: '12'
    tags: true
    repo: urbanmassage/node-rabbitr
  skip_cleanup: true
