language: node_js
node_js:
  - stable
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

services:
  - rabbitmq

script:
  - npm test

after_success:
  - npm run coverage
  - cat ./coverage/lcov-mapped.info | ./node_modules/codecov.io/bin/codecov.io.js
