language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
services:
- rabbitmq
script:
- npm test
after_success:
- test $TRAVIS_NODE_VERSION = "4.1" && npm run coverage && npm run sendcoverage
notifications:
  hipchat:
    rooms:
      secure: YtgcUk4x8EBdac8+vD4VvgImAoOwDmiulQKmkXRxzBTFyJodc+cpVX+bRI/3YY5PyiE1GefFJAKlR23dmRnAn+gBjOBcPu8PlUrSioKvvM4WGCiFJ4SqlrJHVBIUlwQCpThmregGjrpdOAlTmGDcsYrU9XC8kF2jUSAcp3/gOkhtHchKgxSW8sYwqlUg28YnMJhHhWWV0ZF3iuMPDiwlOEElbqnLPj5F9ARKKUqR8XOc+9OFCi6oliYjULAoJ0scliRhSC2+HAAwn95jp+9BozE3oKJY/nY2fawPHilL3GObsEgTxf/CxAY0CvrTYXn2cOhmiIUpxpLFpxIjwWs/vd9zACtu4RxNleQ9897yj78t0HXO7E+YB8/vkkYrOukbntLQsEtIAQrRihcjIgwBo2uMHk8XryqUJ3oB4pPordxVJTsQdG5/L7s9Uyn19Lp3SfUNZa/bdJE/Ylm0JgPz7vDiZlo4ZecvxComynCvpfUaSiXfKUYhC+7Jd/kXzJl06ozKY9aMaoExGqT3w5mcO/zHjC/z2vSoSM5lrI8imm9IC2OScbOSTCv1Mcei8RXdETkhD9yNgRB6GQW2H0nI7d8Lo2YjUxUZ9oBjT+g5njDfeObEXcKecjtj4fuHLCLPv1kXdRajnY1eXN4F+2RdcIY/W7l3H5RKC56dg1BYFCo=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
