language: node_js
node_js:
  - stable
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"

services:
  - rabbitmq

script:
  - npm test
  - npm run coverage -- "--reporter" "mocha-junit-reporter"
  - cat ./coverage/lcov-mapped.info | ./node_modules/codecov.io/bin/codecov.io.js
